apiVersion: v1
kind: Service
metadata:
  name: cloudcomp-corona-backend
  labels:
    app: cloudcomp-corona-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudcomp-corona-backend
