apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/apps.yaml
- resources/certificate.yaml
- resources/ingress.yaml

helmCharts:
- name: argo-cd
  repo: https://charts.bitnami.com/bitnami
  releaseName: argo-cd
  namespace: argocd
  version: 2.0.20
  valuesFile: values.yaml
  includeCRDs: true