apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/ingress.yaml

helmCharts:
  - name: docker-registry
    releaseName: registry
    namespace: registry
    includeCRDs: true
    repo: https://helm.twun.io
    version: 1.16.0
    valuesFile: values.yaml
