name: BUILD_APPLICATION

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.PAT }} 
      
    - name: Set current timestamp
      run: echo "RELEASE_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: registry.guldner.eu
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Frontend
      run: docker build ./frontend --file frontend/Dockerfile --tag registry.guldner.eu/frontend:${{env.RELEASE_DATE}} && docker push registry.guldner.eu/frontend:${{env.RELEASE_DATE}}
    
    - name: Set Frontend Deployment
      run: sed -ie "s/^\(\s*image\s*:\s*\).*/\1registry.guldner.eu\\/frontend:${{env.RELEASE_DATE}}/" ./cluster/frontend/resources/deployment.yaml && cat ./cluster/frontend/resources/deployment.yaml
    
    - name: Build Corona Backend
      run: docker build ./corona-backend --file corona-backend/Dockerfile --tag registry.guldner.eu/corona-backend:${{env.RELEASE_DATE}} && docker push registry.guldner.eu/corona-backend:${{env.RELEASE_DATE}}
      
    - name: Set Corona Backend Deployment
      run: sed -ie "s/^\(\s*image\s*:\s*\).*/\1registry.guldner.eu\\/corona-backend:${{env.RELEASE_DATE}}/" ./cluster/corona-backend/resources/deployment.yaml && cat ./cluster/corona-backend/resources/deployment.yaml
      
    - name: Build Country Backend
      run: docker build ./country-backend --file country-backend/Dockerfile --tag registry.guldner.eu/country-backend:${{env.RELEASE_DATE}} && docker push registry.guldner.eu/country-backend:${{env.RELEASE_DATE}}

    - name: Set Country Backend Deployment
      run: sed -ie "s/^\(\s*image\s*:\s*\).*/\1registry.guldner.eu\\/country-backend:${{env.RELEASE_DATE}}/" ./cluster/country-backend/resources/deployment.yaml && cat ./cluster/country-backend/resources/deployment.yaml

    - name: Commit deployment Files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "[Deployment] Updated Resources"
          branch: deployment
