name: BUILD_APPLICATION

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: echo $GITHUB_SHA

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: registry.guldner.eu
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Frontend
      run: docker build ./frontend --file frontend/Dockerfile --tag registry.guldner.eu/frontend:$GITHUB_SHA && docker push registry.guldner.eu/frontend:$GITHUB_SHA
      
    - name: Build Corona Backend
      run: docker build ./corona-backend --file corona-backend/Dockerfile --tag registry.guldner.eu/corona-backend:$GITHUB_SHA && docker push registry.guldner.eu/corona-backend:$GITHUB_SHA
      
    - name: Build Country Backend
      run: docker build ./country-backend --file country-backend/Dockerfile --tag registry.guldner.eu/country-backend:$GITHUB_SHA && docker push registry.guldner.eu/country-backend:$GITHUB_SHA
